name: Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # use PAT for push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas plotly

      - name: Run script
        run: python main.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if ! git diff --cached --quiet; then
            git commit -m "Update index.html"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/felixdietrich/web.git
            git push origin main
          fi