name: Update

on:
  schedule:
    - cron: '0 * * * *' # runs every hour at minute 0
  workflow_dispatch:

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Python script
        run: python main.py

      - name: Commit & push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if ! git diff --cached --quiet; then
            git commit -m "Update"
            # Push using the GITHUB_TOKEN
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/felixdietrich/web.git HEAD:main
          else
            echo "No changes to commit"
          fi