name: Update

on:
  schedule:
    - cron: '0 * * * *' # runs every hour at minute 0
  workflow_dispatch:

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run
        run: python main.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update" || echo "No changes"
          git push